name: Spellchecking Final Autofix

on: 
  workflow_dispatch:
  repository_dispatch:
    types: [spell-check-workflow]

jobs:
  codespell:
    name: Check spelling with codespell and autofix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]  # Define the Python version here
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
            gpg_private_key: ${{ secrets.CSM_GPG_PRIVATE_KEY }}
            git_user_signingkey: true
            git_commit_gpgsign: true
            git_tag_gpgsign: true
            git_config_global: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell

      - name: Check and fix spelling with codespell
        run: |
          chmod +x .github/workflows/Spell-check-autofix/codespell-autofix.sh
          ./.github/workflows/Spell-check-autofix/codespell-autofix.sh
      
      - name: Check for uncommitted changes
        id: check_changes
        run: |
          git status
          if [ -n "$(git status --porcelain)" ]; then
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          fi

      - name: Print changes detected
        run: |
          echo "Changes detected: ${{ env.CHANGES_DETECTED }}"

      - name: Commit and push changes
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git add .
          git commit -m "Autofix spelling issues"

      - uses: actions/create-github-app-token@v1.11.1
        id: generate-token
        with:
          app-id: ${{ vars.CSM_RELEASE_APP_ID }}
          private-key: ${{ secrets.CSM_RELEASE_APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: autofix-spelling
          title: 'Autofix spelling issues'
          body: "This pull request was created automatically by a GitHub Action that fixes spelling errors."
          sign-commits: true
          delete-branch: true
