name: Spellcheck

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.20.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: "content/**/*.md"