name: Spellcheck

on:
  workflow_dispatch:
  push:
    branches:
      - testing-branch
  pull_request:
    branches:
      - testing-branch

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Spellcheck
        uses: check-spelling/check-spelling@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/spelling/config # Point to the configuration file

      - name: Print Results
        if: failure()
        run: cat ${{ github.workspace }}/.github/spelling/output.txt