name: Spell Checking

on: 
    workflow_dispatch:
    push:
      branches:
        - test-spell2
    pull_request:
      branches:
        - test-spell2
jobs:
  codespell:
    name: Check spelling with codespell
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]  # Define the Python version here
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Check spelling with codespell
        run: find . -type f -name "*.md" -exec codespell --ignore-words=.github/workflows/codespell.txt {} +

  misspell:
    name: Check spelling with misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: Misspell
        run: ./misspell -error $(find . -type f -name "*.md")